development:
  adapter: postgresql
  encoding: unicode
  database: adopt_a_thing_development
  pool: 5

test:
 adapter: postgresql
 encoding: unicode
 database: adopt_a_thing_test
 pool: 5


production:
 adapter: postgresql
 encoding: unicode
 database: adopt_a_thing_production
 pool: 5
