development:
  adapter: postgresql
  encoding: unicode
  database: adopt_a_thing_development
  pool: 5
  username: costantin
  password: p

test:
 adapter: postgresql
 encoding: unicode
 database: adopt_a_thing_test
 pool: 5
 username: costantin
 password: p


production:
 adapter: postgresql
 encoding: unicode
 database: adopt_a_thing_production
 pool: 5
 username: costantin    
 password: p